apiVersion: v1
kind: Service
metadata:
  name: ${CI_PROJECT_NAME}
  namespace: ${K8S_NAMESPACE}
  labels:
    app: ${CI_PROJECT_NAME}
spec:
  type: ClusterIP
  selector:
    app: ${CI_PROJECT_NAME}
  ports:
  - name: 8080-tcp
    protocol: TCP
    port: 8080
    targetPort: 8080
